site_name: Awesome Conversational AI 
site_description: 'a curated list of resources'
site_author: 'Kay Schneutzer & Holger Imbery'
docs_dir: docs/
repo_name: 'assistantbuilders/awesome-conversational-ai'
repo_url: 'https://github.com/assistantbuilders/awesome-conversational-ai'
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Blog: blog.md
    - Resources: resources.md
    - About: about.md
    - License: license.md
theme:
  name: 'material'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/holgerimbery
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/schneutzi81
