site_name: Awesome Conversational AI 
site_description: 'a curated list of resources'
site_author: 'Kay Schneutzer & Holger Imbery'
docs_dir: docs/
repo_name: 'assistantbuilders/awesome-conversational-ai'
repo_url: 'https://github.com/assistantbuilders/awesome-conversational-ai'
edit_uri: edit/main/docs/
nav:
    - Home: index.md
    - Blog: blog.md
    - Resources: resources.md
    - About: about.md
    - License: license.md
theme:
  name: 'material'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/holgerimbery
      name: Holger on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/holgerimbery/
      name: Holger on Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/holgerimbery
      name: Holger on github
  copyright: Copyright &copy; 2021 Kay Schneutzer, Holger Imbery
