site_name: Awesome Conversational AI 
site_description: 'a curated list of resources'
site_url: https://assistantbuilders.github.io/awesome-conversational-ai/
site_author: 'Kay Schneutzer & Holger Imbery'
docs_dir: docs/
repo_name: 'assistantbuilders/awesome-conversational-ai'
repo_url: 'https://github.com/assistantbuilders/awesome-conversational-ai'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2021 Kay Schneutzer

nav:
    - Home: index.md
    #- Blog: blog.md
    - Demos: resources.md
    - About: about.md
    - License: license.md
theme:
  name: 'material'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/schneutzi
      name: Kay on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kay-schneutzer-50169817
      name: Kay on Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/schneutzi81
      name: Kay on github
  disqus: awesome-conversational-ai
